defmodule Tomato.Backend.Flake do
  @moduledoc """
  Flake backend — generates a `flake.nix` with inputs from OODNs
  and nixosConfigurations from the graph walk.

  OODN keys prefixed with `input_` become flake inputs:
    input_nixpkgs = "github:nixos/nixpkgs?ref=nixos-unstable"
    input_home-manager = "github:nix-community/home-manager"

  The `follows` convention: if an OODN key matches `input_NAME_follows`,
  its value is the input to follow:
    input_home-manager_follows = "nixpkgs"
  """

  @doc """
  Wrap composed fragments in a flake.nix skeleton.

  - `fragments` — list of Nix config strings from the walker
  - `oodn` — flat key-value map from OODN registry
  """
  @spec finalize(list(String.t()), map()) :: String.t()
  def finalize(fragments, oodn) do
    hostname = Map.get(oodn, "hostname", "nixos")
    system = Map.get(oodn, "system_arch", "aarch64-linux")
    state_version = Map.get(oodn, "state_version", "24.11")
    keymap = Map.get(oodn, "keymap", "us")

    inputs_nix = build_inputs(oodn)
    input_names = extract_input_names(oodn)
    follows_nix = build_follows(oodn)

    body =
      fragments
      |> Enum.map(fn frag ->
        frag
        |> String.split("\n")
        |> Enum.map(&("          " <> &1))
        |> Enum.join("\n")
      end)
      |> Enum.join("\n\n")

    output = """
    # Generated by Tomato - Hierarchical DAG Engine
    # Do not edit manually

    {
      inputs = {
    #{inputs_nix}#{follows_nix}  };

      outputs = { #{format_output_args(input_names)} }: {
        nixosConfigurations."#{hostname}" = nixpkgs.lib.nixosSystem {
          system = "#{system}";
          modules = [
            ./hardware-configuration.nix
            ({ config, pkgs, lib, ... }: {
              console.keyMap = "#{keymap}";

              # Tomato deploy requires SSH — do not remove
              services.openssh = {
                enable = true;
                settings = {
                  PermitRootLogin = "yes";
                  PasswordAuthentication = true;
                };
              };

              networking.useDHCP = lib.mkDefault true;

              system.stateVersion = "#{state_version}";

    #{body}
            })
          ];
        };
      };
    }
    """

    String.trim(output)
  end

  @doc """
  Generate a flake.nix with nixosConfigurations and/or homeConfigurations.

  - `machine_configs` — list of `{machine_meta, fragments}` tuples,
    already filtered by the walker so each machine only receives
    fragments compatible with its type
  - `nixos_shared` — shared root-level fragments applicable to NixOS
    machines (target `:nixos` or `:all`)
  - `hm_shared` — shared root-level fragments applicable to Home
    Manager machines (target `:home_manager` or `:all`)
  - `oodn` — global OODN map
  """
  @spec finalize_multi(
          list({map(), list(String.t())}),
          list(String.t()),
          list(String.t()),
          map()
        ) :: String.t()
  def finalize_multi(machine_configs, nixos_shared, hm_shared, oodn) do
    keymap = Map.get(oodn, "keymap", "us")
    inputs_nix = build_inputs(oodn)
    input_names = extract_input_names(oodn)
    follows_nix = build_follows(oodn)
    _has_hm = Enum.any?(input_names, &(&1 == "home-manager"))

    nixos_shared_body = indent_fragments(nixos_shared, "          ")
    hm_shared_body = indent_fragments(hm_shared, "          ")

    {nixos_machines, hm_machines} =
      Enum.split_with(machine_configs, fn {machine, _} ->
        Map.get(machine, :type, :nixos) == :nixos
      end)

    nixos_nix = build_nixos_configs(nixos_machines, nixos_shared_body, keymap)
    hm_nix = build_home_configs(hm_machines, hm_shared_body)

    sections =
      []
      |> maybe_add_section(nixos_nix, "nixosConfigurations")
      |> maybe_add_section(hm_nix, "homeConfigurations")
      |> Enum.join("\n\n")

    output = """
    # Generated by Tomato - Hierarchical DAG Engine
    # Do not edit manually

    {
      inputs = {
    #{inputs_nix}#{follows_nix}  };

      outputs = { #{format_output_args(input_names)} }: {
    #{sections}
      };
    }
    """

    String.trim(output)
  end

  defp build_nixos_configs([], _shared, _keymap), do: ""

  defp build_nixos_configs(machines, shared_body, keymap) do
    Enum.map_join(machines, "\n\n", fn {machine, fragments} ->
      hostname = Map.get(machine, :hostname, "nixos")
      system = Map.get(machine, :system, "aarch64-linux")
      sv = Map.get(machine, :state_version, "24.11")
      body = indent_fragments(fragments, "          ")

      raw = """
          "#{hostname}" = nixpkgs.lib.nixosSystem {
            system = "#{system}";
            modules = [
              ({ config, pkgs, lib, ... }: {
                console.keyMap = "#{keymap}";
                networking.hostName = "#{hostname}";

                services.openssh = {
                  enable = true;
                  settings = {
                    PermitRootLogin = "yes";
                    PasswordAuthentication = true;
                  };
                };

                networking.useDHCP = lib.mkDefault true;
                system.stateVersion = "#{sv}";#{compose_body(shared_body, body)}
              })
            ];
          };
      """

      String.trim_trailing(raw)
    end)
  end

  defp build_home_configs([], _shared), do: ""

  defp build_home_configs(machines, shared_body) do
    Enum.map_join(machines, "\n\n", fn {machine, fragments} ->
      hostname = Map.get(machine, :hostname, "nixos")
      username = Map.get(machine, :username, "user")
      system = Map.get(machine, :system, "aarch64-linux")
      body = indent_fragments(fragments, "          ")
      config_name = "#{username}@#{hostname}"

      raw = """
          "#{config_name}" = home-manager.lib.homeManagerConfiguration {
            pkgs = nixpkgs.legacyPackages.#{system};
            modules = [
              ({ config, pkgs, lib, ... }: {
                home.username = "#{username}";
                home.homeDirectory = "/home/#{username}";
                home.stateVersion = "#{Map.get(machine, :state_version, "24.11")}";
                programs.home-manager.enable = true;#{compose_body(shared_body, body)}
              })
            ];
          };
      """

      String.trim_trailing(raw)
    end)
  end

  # Assemble the shared+body section with correct spacing. When both are
  # empty, returns "" so the surrounding template collapses to a direct
  # transition with no blank lines. When one or both are present, returns
  # "\n\n<content>" — the leading "\n\n" provides exactly one blank line
  # after the preceding line, and parts are joined by one blank line.
  defp compose_body(shared, body) do
    [shared, body]
    |> Enum.reject(&(&1 == ""))
    |> case do
      [] -> ""
      parts -> "\n\n" <> Enum.join(parts, "\n\n")
    end
  end

  defp maybe_add_section(sections, "", _name), do: sections

  defp maybe_add_section(sections, content, name) do
    sections ++ ["    #{name} = {\n#{content}\n    };"]
  end

  # --- Private ---

  defp build_inputs(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} ->
      String.starts_with?(k, "input_") and not String.contains?(k, "_follows")
    end)
    |> Enum.sort_by(fn {k, _} -> k end)
    |> Enum.map(fn {key, url} ->
      name = String.replace_prefix(key, "input_", "")
      "    #{name}.url = \"#{url}\";"
    end)
    |> Enum.join("\n")
    |> case do
      "" -> ""
      lines -> lines <> "\n"
    end
  end

  defp build_follows(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} -> String.contains?(k, "_follows") end)
    |> Enum.sort_by(fn {k, _} -> k end)
    |> Enum.map(fn {key, target} ->
      # input_home-manager_follows = "nixpkgs" → home-manager.inputs.nixpkgs.follows = "nixpkgs"
      name =
        key
        |> String.replace_prefix("input_", "")
        |> String.replace_suffix("_follows", "")

      "    #{name}.inputs.nixpkgs.follows = \"#{target}\";"
    end)
    |> Enum.join("\n")
    |> case do
      "" -> ""
      lines -> lines <> "\n"
    end
  end

  defp extract_input_names(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} ->
      String.starts_with?(k, "input_") and not String.contains?(k, "_follows")
    end)
    |> Enum.map(fn {key, _} -> String.replace_prefix(key, "input_", "") end)
    |> Enum.sort()
  end

  defp indent_fragments(fragments, prefix) do
    fragments
    |> Enum.map(fn frag ->
      frag
      |> String.split("\n")
      |> Enum.map(&(prefix <> &1))
      |> Enum.join("\n")
    end)
    |> Enum.join("\n\n")
  end

  defp format_output_args(input_names) do
    names = Enum.join(input_names, ", ")

    if names == "" do
      "nixpkgs, ..."
    else
      "#{names}, ..."
    end
  end
end
