defmodule Tomato.Backend.Flake do
  @moduledoc """
  Flake backend — generates a `flake.nix` with inputs from OODNs
  and nixosConfigurations from the graph walk.

  OODN keys prefixed with `input_` become flake inputs:
    input_nixpkgs = "github:nixos/nixpkgs?ref=nixos-unstable"
    input_home-manager = "github:nix-community/home-manager"

  The `follows` convention: if an OODN key matches `input_NAME_follows`,
  its value is the input to follow:
    input_home-manager_follows = "nixpkgs"
  """

  @doc """
  Wrap composed fragments in a flake.nix skeleton.

  - `fragments` — list of Nix config strings from the walker
  - `oodn` — flat key-value map from OODN registry
  """
  @spec finalize(list(String.t()), map()) :: String.t()
  def finalize(fragments, oodn) do
    hostname = Map.get(oodn, "hostname", "nixos")
    system = Map.get(oodn, "system_arch", "aarch64-linux")
    state_version = Map.get(oodn, "state_version", "24.11")
    keymap = Map.get(oodn, "keymap", "us")

    inputs_nix = build_inputs(oodn)
    input_names = extract_input_names(oodn)
    follows_nix = build_follows(oodn)

    body =
      fragments
      |> Enum.map(fn frag ->
        frag
        |> String.split("\n")
        |> Enum.map(&("          " <> &1))
        |> Enum.join("\n")
      end)
      |> Enum.join("\n\n")

    """
    # Generated by Tomato - Hierarchical DAG Engine
    # Do not edit manually

    {
      inputs = {
    #{inputs_nix}#{follows_nix}  };

      outputs = { #{format_output_args(input_names)} }: {
        nixosConfigurations."#{hostname}" = nixpkgs.lib.nixosSystem {
          system = "#{system}";
          modules = [
            ./hardware-configuration.nix
            ({ config, pkgs, lib, ... }: {
              console.keyMap = "#{keymap}";

              # Tomato deploy requires SSH — do not remove
              services.openssh = {
                enable = true;
                settings = {
                  PermitRootLogin = "yes";
                  PasswordAuthentication = true;
                };
              };

              networking.useDHCP = lib.mkDefault true;

              system.stateVersion = "#{state_version}";

    #{body}
            })
          ];
        };
      };
    }
    """
    |> String.trim()
  end

  @doc """
  Generate a flake.nix with multiple nixosConfigurations.

  - `machine_configs` — list of {machine_meta, fragments} tuples
  - `shared_fragments` — fragments from non-machine nodes at root level
  - `oodn` — global OODN map
  """
  @spec finalize_multi(list({map(), list(String.t())}), list(String.t()), map()) :: String.t()
  def finalize_multi(machine_configs, shared_fragments, oodn) do
    keymap = Map.get(oodn, "keymap", "us")
    inputs_nix = build_inputs(oodn)
    input_names = extract_input_names(oodn)
    follows_nix = build_follows(oodn)

    shared_body = indent_fragments(shared_fragments, "          ")

    machines_nix =
      machine_configs
      |> Enum.map(fn {machine, fragments} ->
        hostname = Map.get(machine, :hostname, "nixos")
        system = Map.get(machine, :system, "aarch64-linux")
        sv = Map.get(machine, :state_version, "24.11")
        body = indent_fragments(fragments, "          ")

        """
            "#{hostname}" = nixpkgs.lib.nixosSystem {
              system = "#{system}";
              modules = [
                ({ config, pkgs, lib, ... }: {
                  console.keyMap = "#{keymap}";
                  networking.hostName = "#{hostname}";

                  services.openssh = {
                    enable = true;
                    settings = {
                      PermitRootLogin = "yes";
                      PasswordAuthentication = true;
                    };
                  };

                  networking.useDHCP = lib.mkDefault true;
                  system.stateVersion = "#{sv}";

        #{shared_body}

        #{body}
                })
              ];
            };
        """
        |> String.trim_trailing()
      end)
      |> Enum.join("\n\n")

    """
    # Generated by Tomato - Hierarchical DAG Engine
    # Do not edit manually

    {
      inputs = {
    #{inputs_nix}#{follows_nix}  };

      outputs = { #{format_output_args(input_names)} }: {
        nixosConfigurations = {
    #{machines_nix}
        };
      };
    }
    """
    |> String.trim()
  end

  # --- Private ---

  defp build_inputs(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} ->
      String.starts_with?(k, "input_") and not String.contains?(k, "_follows")
    end)
    |> Enum.sort_by(fn {k, _} -> k end)
    |> Enum.map(fn {key, url} ->
      name = String.replace_prefix(key, "input_", "")
      "    #{name}.url = \"#{url}\";"
    end)
    |> Enum.join("\n")
    |> case do
      "" -> ""
      lines -> lines <> "\n"
    end
  end

  defp build_follows(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} -> String.contains?(k, "_follows") end)
    |> Enum.sort_by(fn {k, _} -> k end)
    |> Enum.map(fn {key, target} ->
      # input_home-manager_follows = "nixpkgs" → home-manager.inputs.nixpkgs.follows = "nixpkgs"
      name =
        key
        |> String.replace_prefix("input_", "")
        |> String.replace_suffix("_follows", "")

      "    #{name}.inputs.nixpkgs.follows = \"#{target}\";"
    end)
    |> Enum.join("\n")
    |> case do
      "" -> ""
      lines -> lines <> "\n"
    end
  end

  defp extract_input_names(oodn) do
    oodn
    |> Enum.filter(fn {k, _v} ->
      String.starts_with?(k, "input_") and not String.contains?(k, "_follows")
    end)
    |> Enum.map(fn {key, _} -> String.replace_prefix(key, "input_", "") end)
    |> Enum.sort()
  end

  defp indent_fragments(fragments, prefix) do
    fragments
    |> Enum.map(fn frag ->
      frag
      |> String.split("\n")
      |> Enum.map(&(prefix <> &1))
      |> Enum.join("\n")
    end)
    |> Enum.join("\n\n")
  end

  defp format_output_args(input_names) do
    names = Enum.join(input_names, ", ")

    if names == "" do
      "nixpkgs, ..."
    else
      "#{names}, ..."
    end
  end
end
