defmodule Tomato.Walker do
  @moduledoc """
  Traverses the graph top-down via topological sort and produces
  composed Nix output from leaf node content.

  OODN (Out-Of-DAG Node) values are interpolated into every leaf node's
  content via `${key}` placeholders. The OODN map is built once at walk
  start and carried unchanged to every depth.
  """

  alias Tomato.{Graph, Subgraph, Constraint}

  @doc """
  Walk the entire graph starting from the root subgraph.
  Returns the generated configuration.nix string.
  """
  @spec walk(Graph.t()) :: String.t()
  def walk(%Graph{} = graph) do
    oodn = build_oodn_map(graph)
    root = Graph.root_subgraph(graph)
    fragments = walk_subgraph(root, graph, oodn)
    finalize(fragments, oodn)
  end

  @doc """
  Build a flat key→value map from the graph's OODN registry.
  """
  @spec build_oodn_map(Graph.t()) :: map()
  def build_oodn_map(%Graph{oodn_registry: registry}) do
    registry
    |> Map.values()
    |> Map.new(fn %{key: k, value: v} -> {k, v} end)
  end

  @doc """
  Walk a single subgraph, recursing into gateways.
  The oodn map is passed unchanged at every depth.
  """
  @spec walk_subgraph(Subgraph.t(), Graph.t(), map()) :: list(String.t())
  def walk_subgraph(%Subgraph{} = sg, %Graph{} = graph, oodn) do
    case Constraint.topological_sort(sg) do
      {:ok, sorted_ids} ->
        Enum.flat_map(sorted_ids, fn node_id ->
          node = Map.get(sg.nodes, node_id)
          collect_fragments(node, graph, oodn)
        end)

      {:error, _, _} ->
        []
    end
  end

  defp collect_fragments(%{type: :leaf, content: content}, _graph, oodn)
       when is_binary(content) and content != "" do
    [interpolate(String.trim(content), oodn)]
  end

  defp collect_fragments(%{type: :gateway, subgraph_id: sg_id}, graph, oodn)
       when is_binary(sg_id) do
    case Graph.get_subgraph(graph, sg_id) do
      nil -> []
      child_sg -> walk_subgraph(child_sg, graph, oodn)
    end
  end

  defp collect_fragments(_node, _graph, _oodn), do: []

  @doc """
  Interpolate `${key}` placeholders in content with OODN values.
  Unknown keys are left as-is.
  """
  @spec interpolate(String.t(), map()) :: String.t()
  def interpolate(content, oodn) do
    Regex.replace(~r/\$\{(\w+)\}/, content, fn _match, key ->
      Map.get(oodn, key, "${#{key}}")
    end)
  end

  @doc """
  Wrap fragments in a NixOS module skeleton.
  Skeleton values are also driven by OODNs where available.
  """
  @spec finalize(list(String.t()), map()) :: String.t()
  def finalize(fragments, oodn) do
    keymap = Map.get(oodn, "keymap", "us")
    state_version = Map.get(oodn, "state_version", "24.11")

    body =
      fragments
      |> Enum.map(fn frag ->
        frag
        |> String.split("\n")
        |> Enum.map(&("  " <> &1))
        |> Enum.join("\n")
      end)
      |> Enum.join("\n\n")

    """
    # Generated by Tomato - Hierarchical DAG Engine
    # Do not edit manually

    { config, pkgs, lib, ... }:
    {
      imports = [ ./hardware-configuration.nix ];

      boot.loader.systemd-boot.enable = true;
      boot.loader.efi.canTouchEfiVariables = true;

      console.keyMap = "#{keymap}";

      # Tomato deploy requires SSH — do not remove
      services.openssh = {
        enable = true;
        settings = {
          PermitRootLogin = "yes";
          PasswordAuthentication = true;
        };
      };

      networking.useDHCP = lib.mkDefault true;

      system.stateVersion = "#{state_version}";

    #{body}
    }
    """
    |> String.trim()
  end
end
